let suggestions = [
    "Coronavirus",
     "Influenza",
      "Diabetes",
       "Cancer",
        "Anxiety",
         "Depression",
          "Heart Disease",
           "Back Pain",
            "High Blood Pressure",
             "Thyroid Disease",
             "Women's health", "Men's health", "Sexual health", "Reproductive health", "Pediatrics", "Geriatrics", "Nutrition and dietetics", "Gastroenterology", "Endocrinology", "Hematology", "Pulmonology", "Rheumatology", "Ophthalmology", "Otolaryngology", "Urology", "Obstetrics and gynecology", "Fertility treatments", "Pregnancy", "Childbirth", "Neonatology", "Autism spectrum disorder", "Schizophrenia", "Bipolar disorder", "Post-traumatic stress disorder (PTSD)", "Obsessive-compulsive disorder (OCD)", "Eating disorders", "Sleep disorders", "Chronic fatigue syndrome", "Fibromyalgia", "Chronic obstructive pulmonary disease (COPD)", "Liver disease", "Kidney disease", "Thyroid disorders", "Infectious diseases", "Sexually transmitted infections (STIs)", "HIV/AIDS", "Hepatitis", "Tuberculosis", "Lyme disease", "Influenza", "COVID-19", "Neurological disorders", "Stroke", "Traumatic brain injury", "Dementia", "Eating healthy on a budget", "Exercises for different body parts", "Meditation techniques", "Stress management", "Mental health first aid",
             "Acetaminophen (Tylenol)", "Aspirin (Bayer, Bufferin)", "Ibuprofen (Advil, Motrin)", "Naproxen (Aleve)", "Simvastatin (Zocor)", "Atorvastatin (Lipitor)", "Lisinopril (Zestril, Prinivil)", "Amlodipine (Norvasc)", "Metoprolol (Lopressor, Toprol)", "Losartan (Cozaar)", "Metformin (Glucophage)", "Omeprazole (Prilosec)", "Pantoprazole (Protonix)", "Lansoprazole (Prevacid)", "Esomeprazole (Nexium)", "Citalopram (Celexa)", "Sertraline (Zoloft)", "Escitalopram (Lexapro)", "Fluoxetine (Prozac)", "Paroxetine (Paxil)", "Bupropion (Wellbutrin)", "Duloxetine (Cymbalta)", "Venlafaxine (Effexor)", "Alprazolam (Xanax)", "Clonazepam (Klonopin)", "Diazepam (Valium)", "Lorazepam (Ativan)", "Gabapentin (Neurontin)", "Pregabalin (Lyrica)", "Tramadol (Ultram)", "Oxycodone (OxyContin)", "Hydrocodone/acetaminophen (Vicodin, Norco)", "Codeine/acetaminophen (Tylenol with codeine)", "Fentanyl (Duragesic)", "Morphine (MS Contin)", "Warfarin (Coumadin)", "Clopidogrel (Plavix)", "Rivaroxaban (Xarelto)", "Apixaban (Eliquis)", "Dabigatran (Pradaxa)", "Insulin glargine (Lantus)", "Insulin lispro (Humalog)", "Insulin aspart (Novolog)", "Levothyroxine (Synthroid)", "Methotrexate (Trexall)", "Azathioprine (Imuran)", "Cyclosporine (Neoral, Sandimmune)", "Tacrolimus (Prograf)", "Prednisone (Deltasone)", "Hydrocortisone (Cortef)", "Methylprednisolone (Medrol)", "Montelukast (Singulair)", "Fluticasone (Flonase)", "Budesonide (Pulmicort)", "Albuterol (Proventil, Ventolin)", "Ipratropium/albuterol (Combivent)", "Beclomethasone (Qvar)", "Tiotropium (Spiriva)", "Loratadine (Claritin)", "Cetirizine (Zyrtec)", "Fexofenadine (Allegra)", "Diphenhydramine (Benadryl)", "Acyclovir (Zovirax)", "Valacyclovir (Valtrex)", "Oseltamivir (Tamiflu)", "Amoxicillin (Amoxil)", "Cephalexin (Keflex)","malaria","dengue","disprin","paracetamol",
];
